### ISSUE TITLE
Incorrect width for 3 different tape types

### ISSUE THREAD

**Issue by Natsukooh** [ryankurte/rust-ptouch#33]
Hi,

While trying to add a new feature (the switch to bypass the status request you suggested [here](https://github.com/ryankurte/rust-ptouch/issues/31#issuecomment-1190803541)), I noticed something that looks like a bug: in [the device.rs file, in method width](https://github.com/ryankurte/rust-ptouch/blob/2e2e4ff957b0bf8f8790e4274bbd5456ef7dd3cf/src/device.rs#L132), you return a width based on the model of `self` ; but the width for 3 of them seems to miss a digit:
```rust
Tze12mm => 2,
Tze18mm => 8,
Tze24mm => 4,
```
That probably should be 12, 18 and 24, right ?
Fortunately, it looks like this method is not used anywhere. It is still good that you implemented it, because it turns out I needed it for the feature I'm adding.

Anyway, I am fixing this in the pull request I'm gonna open for the new feature.

**Comment by ryankurte** [comment]
good catch! looks like a typeo to me
